---
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
title: Status Row
subtitle: Tackling plastic pollution head on in an effort to save our oceans.
url: http://www.statusrow.com/
baseurl: ''
cover: "/assets/cover.png"
logo: "/assets/images/logo_small.jpg"
markdown: kramdown
ga_tracking_id: UA-102604973-1
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
timezone: Etc/UTC
